const $=s=>document.querySelector(s); const key=()=>$('#key').value;
$('#key').value=sessionStorage.getItem('pipedalAiKey')||'';
async function api(path,options={}){options.headers={...(options.headers||{}),'X-PiPedal-AI-Key':key()};const r=await fetch(path,options);if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail);return r.status===204?null:r.json()}
async function refresh(){try{const [status,profiles,jobs]=await Promise.all([api('/api/v1/status'),api('/api/v1/profiles'),api('/api/v1/jobs')]);$('#health').textContent=`${status.rtx_available?'RTX IA':'mode local'} · ${status.pipedal_available?'PiPedal OK':'PiPedal hors ligne'}`;const current=$('#profile').value;$('#profile').innerHTML='<option value="">Profil par défaut</option>'+profiles.map(p=>`<option value="${p.profile_id}">${escapeHtml(p.name)}</option>`).join('');$('#profile').value=current;renderProfiles(profiles);renderJobs(jobs)}catch(e){$('#health').textContent='authentification requise'}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderProfiles(profiles){$('#profileList').innerHTML=profiles.map(p=>`<div class="profile-row"><span><strong>${escapeHtml(p.name)}</strong> · ${escapeHtml(p.guitar||'guitare non précisée')} · ${escapeHtml(p.pickup)} · ${p.input_trim_db} dB</span><button class="secondary delete-profile" data-id="${p.profile_id}">Supprimer</button></div>`).join('');document.querySelectorAll('.delete-profile').forEach(b=>b.onclick=async()=>{if(!confirm('Supprimer ce profil ?'))return;b.disabled=true;try{await api(`/api/v1/profiles/${b.dataset.id}`,{method:'DELETE'});await refresh()}catch(e){alert(e.message)}finally{b.disabled=false}})}
function renderJobs(jobs){$('#jobs').innerHTML=jobs.map(j=>`<article class="job"><h3>${escapeHtml(j.prompt)}</h3><div class="meta">${j.status} · ${j.source} · catalogue r${j.catalog.revision}</div>${j.fallback_reason?`<details class="error"><summary>Mode local utilisé — l’IA RTX n’a pas fourni de proposition validée</summary><p>${escapeHtml(j.fallback_reason)}</p></details>`:''}${j.error?`<p class="error">${escapeHtml(j.error)}</p>`:''}<div class="artifacts">${j.artifacts.map(a=>`<a class="download" href="/api/v1/artifacts/${a.artifact_id}/download" data-id="${a.artifact_id}">${a.variant} ↓</a><button class="secondary import" data-id="${a.artifact_id}">Importer</button>${a.imported_instance_id!==null?`<button class="secondary activate" data-id="${a.artifact_id}">Activer</button>`:''}`).join('')}</div></article>`).join('');document.querySelectorAll('.download').forEach(a=>a.onclick=async e=>{e.preventDefault();const r=await fetch(a.href,{headers:{'X-PiPedal-AI-Key':key()}});if(!r.ok)return alert('Téléchargement refusé');const b=await r.blob(),u=URL.createObjectURL(b),x=document.createElement('a');x.href=u;x.download=r.headers.get('content-disposition')?.match(/filename="?([^";]+)/)?.[1]||'preset.piPreset';x.click();URL.revokeObjectURL(u)});document.querySelectorAll('.import').forEach(b=>b.onclick=()=>action(b,'import'));document.querySelectorAll('.activate').forEach(b=>b.onclick=()=>action(b,'activate'))}
async function action(button,verb){button.disabled=true;try{await api(`/api/v1/artifacts/${button.dataset.id}/${verb}`,{method:'POST'});await refresh()}catch(e){alert(e.message)}finally{button.disabled=false}}
$('#generate').onclick=async()=>{sessionStorage.setItem('pipedalAiKey',key());const msg=$('#message');msg.className='';msg.textContent='Génération en cours…';try{await api('/api/v1/jobs/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:$('#prompt').value,profile_id:$('#profile').value||null,auto_import:$('#autoImport').checked,auto_activate:$('#autoActivate').checked})});msg.textContent='Travail lancé.';await refresh()}catch(e){msg.className='error';msg.textContent=e.message}};$('#autoActivate').onchange=()=>{if($('#autoActivate').checked)$('#autoImport').checked=true};setInterval(refresh,3000);refresh();
$('#createProfile').onclick=async()=>{sessionStorage.setItem('pipedalAiKey',key());const button=$('#createProfile');button.disabled=true;try{await api('/api/v1/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#profileName').value,guitar:$('#profileGuitar').value,pickup:$('#profilePickup').value,input_trim_db:Number($('#profileTrim').value),notes:$('#profileNotes').value})});$('#profileName').value='';$('#profileGuitar').value='';$('#profileNotes').value='';await refresh()}catch(e){alert(e.message)}finally{button.disabled=false}};
